os:
  - linux
language: python
python: 2.7
branches:
  only:
  - release
addons:
  apt:
    packages:
    - unzip
before_install:
  - wget -q -O /tmp/z3.zip https://github.com/Z3Prover/bin/raw/master/releases/z3-4.4.0-x64-ubuntu-14.04.zip
  - mkdir z3
  - unzip -q -d z3 -j /tmp/z3.zip
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/z3
install:
  - python setup.py install
  - pip install tox
script:
  - tox
env:
  - TOXENV=py27
  - TOXENV=py27-full
